// lib/handshape-data.ts
//
// CONFIDENCE LEVELS:
//
// [data-derived] -- computed from real, actual captured hand-landmark samples
//   (median joint angle across ~1,800-2,000 samples per letter from a public
//   ISL hand-landmarks dataset). This is the strongest tier we have: it's
//   math computed from a real signer's hand, not a guess or a text description.
//   The single-handed vs two-handed split per letter was cross-checked
//   against independent published literature (C is single-handed, M/N are
//   two-handed) and matched exactly, which is a good confidence signal for
//   the correctness of the letter-to-class mapping in the source dataset.
//
// [convention] -- based on the general finger-counting logic common to
//   ISL/IPSL numbers (1 finger = one, 2 fingers = two, etc). Reasonable
//   default, not verified against real captured data. Regional counting
//   conventions in India can start from the thumb in some contexts --
//   worth a quick sanity check against ISLRTC video before treating as final.
//
// [placeholder-unconfirmed] -- no reliable source found. Uniform neutral
//   rest pose. DO NOT treat as a real sign.

export type FingerPose = {
  mcp: number;
  pip: number;
  dip: number;
  abduction: number;
};

export type HandPose = {
  thumb: FingerPose;
  index: FingerPose;
  middle: FingerPose;
  ring: FingerPose;
  pinky: FingerPose;
  wristRotation: number;
  handOrientation: 'palm-out' | 'palm-in' | 'side';
};

export type HandshapeEntry = {
  signId: string;
  hands: 'one' | 'two';
  confidence: 'data-derived' | 'convention' | 'placeholder-unconfirmed';
  sourceNote: string;
  primary: HandPose;
  secondary?: HandPose;
};

export const HANDSHAPE_DATA: HandshapeEntry[] = [
  // --- ALPHABET: A-Z, all data-derived from real captured landmark samples ---
  {
    signId: 'A',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 2000 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 25.7, pip: 7.1, dip: 0.0, abduction: 129.9 },
      index: { mcp: 85.2, pip: 86.7, dip: 39.6, abduction: -2.0 },
      middle: { mcp: 103.9, pip: 92.4, dip: 69.4, abduction: 0.0 },
      ring: { mcp: 104.5, pip: 98.0, dip: 67.7, abduction: 4.1 },
      pinky: { mcp: 99.6, pip: 93.5, dip: 65.2, abduction: 14.8 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 24.2, pip: 4.5, dip: 0.0, abduction: -122.4 },
      index: { mcp: 88.0, pip: 85.9, dip: 61.5, abduction: 4.9 },
      middle: { mcp: 103.8, pip: 87.2, dip: 84.4, abduction: 0.0 },
      ring: { mcp: 105.9, pip: 93.2, dip: 79.7, abduction: -4.4 },
      pinky: { mcp: 86.0, pip: 113.9, dip: 54.7, abduction: -18.5 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'B',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1965 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 25.5, pip: 13.9, dip: 0.0, abduction: 58.0 },
      index: { mcp: 37.8, pip: 76.3, dip: 31.7, abduction: -1.0 },
      middle: { mcp: 41.0, pip: 79.9, dip: 33.3, abduction: 0.0 },
      ring: { mcp: 33.6, pip: 83.8, dip: 33.2, abduction: 5.0 },
      pinky: { mcp: 34.4, pip: 67.0, dip: 33.1, abduction: 10.5 },
      wristRotation: 0,
      handOrientation: 'side',
    },
    secondary: {
      thumb: { mcp: 25.6, pip: 15.9, dip: 0.0, abduction: -56.4 },
      index: { mcp: 47.2, pip: 72.8, dip: 28.5, abduction: -1.0 },
      middle: { mcp: 49.6, pip: 77.8, dip: 31.0, abduction: 0.0 },
      ring: { mcp: 42.0, pip: 83.5, dip: 29.1, abduction: -4.3 },
      pinky: { mcp: 45.6, pip: 67.6, dip: 29.5, abduction: -7.7 },
      wristRotation: 0,
      handOrientation: 'side',
    },
  },
  {
    signId: 'C',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 1994 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 21.3, pip: 12.7, dip: 0.0, abduction: 85.8 },
      index: { mcp: 22.3, pip: 44.8, dip: 28.6, abduction: 74.6 },
      middle: { mcp: 101.9, pip: 75.1, dip: 62.2, abduction: 0.0 },
      ring: { mcp: 115.2, pip: 75.3, dip: 73.3, abduction: -1.0 },
      pinky: { mcp: 118.0, pip: 68.4, dip: 72.1, abduction: -0.4 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'D',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1961 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 22.2, pip: 13.7, dip: 0.0, abduction: -93.6 },
      index: { mcp: 16.8, pip: 3.4, dip: 3.1, abduction: -102.6 },
      middle: { mcp: 90.9, pip: 66.2, dip: 44.8, abduction: 0.0 },
      ring: { mcp: 109.5, pip: 74.2, dip: 60.6, abduction: 3.2 },
      pinky: { mcp: 110.8, pip: 67.8, dip: 70.2, abduction: 1.4 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 24.1, pip: 13.2, dip: 0.0, abduction: 93.2 },
      index: { mcp: 28.1, pip: 24.1, dip: 17.2, abduction: 91.0 },
      middle: { mcp: 103.7, pip: 74.4, dip: 63.6, abduction: 0.0 },
      ring: { mcp: 113.5, pip: 77.9, dip: 70.4, abduction: -0.1 },
      pinky: { mcp: 111.9, pip: 72.2, dip: 71.4, abduction: -0.6 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'E',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1997 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 20.9, pip: 19.0, dip: 0.0, abduction: 66.8 },
      index: { mcp: 40.1, pip: 16.6, dip: 8.3, abduction: 77.6 },
      middle: { mcp: 96.2, pip: 81.6, dip: 68.4, abduction: 0.0 },
      ring: { mcp: 100.4, pip: 92.4, dip: 68.0, abduction: -6.9 },
      pinky: { mcp: 91.4, pip: 85.8, dip: 69.5, abduction: -8.8 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 22.1, pip: 21.3, dip: 0.0, abduction: -82.6 },
      index: { mcp: 27.5, pip: 31.4, dip: 20.2, abduction: -83.1 },
      middle: { mcp: 100.7, pip: 72.6, dip: 61.0, abduction: 0.0 },
      ring: { mcp: 107.6, pip: 80.6, dip: 62.7, abduction: 2.9 },
      pinky: { mcp: 101.0, pip: 75.8, dip: 61.4, abduction: -6.7 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'F',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1998 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 43.4, pip: 37.7, dip: 0.0, abduction: -20.1 },
      index: { mcp: 60.8, pip: 3.7, dip: 2.6, abduction: -0.5 },
      middle: { mcp: 54.5, pip: 4.1, dip: 4.4, abduction: 0.0 },
      ring: { mcp: 51.8, pip: 131.9, dip: 34.5, abduction: -3.0 },
      pinky: { mcp: 48.2, pip: 127.9, dip: 36.8, abduction: 14.2 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 39.4, pip: 31.3, dip: 0.0, abduction: 3.1 },
      index: { mcp: 51.1, pip: 12.0, dip: 6.4, abduction: -0.1 },
      middle: { mcp: 47.3, pip: 6.6, dip: 3.2, abduction: 0.0 },
      ring: { mcp: 39.2, pip: 140.5, dip: 26.8, abduction: 6.2 },
      pinky: { mcp: 42.6, pip: 121.6, dip: 33.4, abduction: -17.2 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'G',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1869 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 27.9, pip: 27.2, dip: 0.0, abduction: -39.0 },
      index: { mcp: 80.0, pip: 94.7, dip: 56.1, abduction: 5.2 },
      middle: { mcp: 78.2, pip: 115.5, dip: 49.5, abduction: 0.0 },
      ring: { mcp: 70.5, pip: 127.3, dip: 36.9, abduction: -6.8 },
      pinky: { mcp: 61.2, pip: 118.9, dip: 35.3, abduction: -22.4 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 35.1, pip: 37.8, dip: 0.0, abduction: 29.8 },
      index: { mcp: 81.4, pip: 96.3, dip: 61.3, abduction: -1.1 },
      middle: { mcp: 77.3, pip: 117.3, dip: 51.8, abduction: 0.0 },
      ring: { mcp: 62.9, pip: 123.0, dip: 43.6, abduction: -0.5 },
      pinky: { mcp: 51.7, pip: 127.2, dip: 37.7, abduction: 0.7 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'H',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1833 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 23.7, pip: 11.6, dip: 0.0, abduction: -30.0 },
      index: { mcp: 37.3, pip: 4.7, dip: 4.2, abduction: 1.3 },
      middle: { mcp: 28.8, pip: 4.3, dip: 3.4, abduction: 0.0 },
      ring: { mcp: 18.0, pip: 2.5, dip: 3.5, abduction: -2.7 },
      pinky: { mcp: 22.1, pip: 4.7, dip: 2.9, abduction: -6.3 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 30.8, pip: 16.4, dip: 0.0, abduction: 2.9 },
      index: { mcp: 19.7, pip: 5.3, dip: 2.5, abduction: -1.6 },
      middle: { mcp: 11.4, pip: 6.1, dip: 3.0, abduction: 0.0 },
      ring: { mcp: 7.3, pip: 4.6, dip: 4.6, abduction: 2.8 },
      pinky: { mcp: 12.1, pip: 7.1, dip: 4.7, abduction: 1.5 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'I',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 1994 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 24.9, pip: 14.5, dip: 0.0, abduction: -2.9 },
      index: { mcp: 17.6, pip: 3.8, dip: 4.8, abduction: 25.9 },
      middle: { mcp: 67.9, pip: 98.4, dip: 42.7, abduction: 0.0 },
      ring: { mcp: 79.8, pip: 98.4, dip: 48.5, abduction: 0.2 },
      pinky: { mcp: 78.9, pip: 93.1, dip: 48.4, abduction: -1.4 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'J',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1969 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 11.8, pip: 6.0, dip: 0.0, abduction: -103.0 },
      index: { mcp: 59.9, pip: 3.5, dip: 5.1, abduction: -38.5 },
      middle: { mcp: 59.4, pip: 133.0, dip: 28.3, abduction: 0.0 },
      ring: { mcp: 40.3, pip: 153.8, dip: 22.1, abduction: 5.5 },
      pinky: { mcp: 39.6, pip: 156.3, dip: 14.9, abduction: 17.6 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 7.2, pip: 35.3, dip: 0.0, abduction: -5.7 },
      index: { mcp: 63.4, pip: 14.6, dip: 11.3, abduction: 23.3 },
      middle: { mcp: 136.3, pip: 24.7, dip: 31.4, abduction: 0.0 },
      ring: { mcp: 145.1, pip: 39.0, dip: 47.4, abduction: -0.4 },
      pinky: { mcp: 139.4, pip: 32.5, dip: 41.5, abduction: 1.7 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'K',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 2000 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 22.2, pip: 13.5, dip: 0.0, abduction: -58.3 },
      index: { mcp: 13.9, pip: 4.1, dip: 4.5, abduction: -117.7 },
      middle: { mcp: 88.2, pip: 77.7, dip: 50.3, abduction: 0.0 },
      ring: { mcp: 99.4, pip: 83.3, dip: 55.2, abduction: -1.9 },
      pinky: { mcp: 93.4, pip: 79.0, dip: 57.8, abduction: -5.0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 16.6, pip: 17.3, dip: 0.0, abduction: 37.2 },
      index: { mcp: 45.2, pip: 40.8, dip: 27.6, abduction: 29.4 },
      middle: { mcp: 88.0, pip: 87.4, dip: 66.3, abduction: 0.0 },
      ring: { mcp: 91.6, pip: 109.3, dip: 57.0, abduction: -2.6 },
      pinky: { mcp: 85.0, pip: 107.3, dip: 59.1, abduction: -4.6 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'L',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 2000 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 18.3, pip: 11.7, dip: 0.0, abduction: 55.2 },
      index: { mcp: 20.1, pip: 6.8, dip: 4.0, abduction: -136.9 },
      middle: { mcp: 50.3, pip: 120.0, dip: 43.0, abduction: 0.0 },
      ring: { mcp: 77.9, pip: 105.2, dip: 72.4, abduction: 0.7 },
      pinky: { mcp: 67.9, pip: 110.0, dip: 48.0, abduction: 8.0 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'M',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1911 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 17.0, pip: 6.0, dip: 0.0, abduction: -35.0 },
      index: { mcp: 39.8, pip: 4.4, dip: 3.5, abduction: 2.3 },
      middle: { mcp: 26.1, pip: 2.9, dip: 2.2, abduction: 0.0 },
      ring: { mcp: 14.8, pip: 2.3, dip: 2.3, abduction: -3.7 },
      pinky: { mcp: 26.3, pip: 4.6, dip: 2.1, abduction: -6.9 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 31.8, pip: 62.7, dip: 0.0, abduction: 59.7 },
      index: { mcp: 10.0, pip: 3.8, dip: 1.9, abduction: -5.2 },
      middle: { mcp: 7.3, pip: 8.7, dip: 2.6, abduction: 0.0 },
      ring: { mcp: 9.7, pip: 9.5, dip: 6.0, abduction: -2.5 },
      pinky: { mcp: 69.1, pip: 54.7, dip: 12.3, abduction: -109.8 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'N',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1928 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 24.6, pip: 21.6, dip: 0.0, abduction: -14.0 },
      index: { mcp: 16.5, pip: 4.2, dip: 5.8, abduction: 1.8 },
      middle: { mcp: 20.8, pip: 7.0, dip: 3.8, abduction: 0.0 },
      ring: { mcp: 37.8, pip: 109.7, dip: 34.7, abduction: 20.5 },
      pinky: { mcp: 53.5, pip: 99.0, dip: 41.0, abduction: 27.7 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 22.9, pip: 12.8, dip: 0.0, abduction: 30.0 },
      index: { mcp: 18.9, pip: 9.4, dip: 5.4, abduction: 0.2 },
      middle: { mcp: 13.1, pip: 6.9, dip: 5.6, abduction: 0.0 },
      ring: { mcp: 7.1, pip: 3.3, dip: 4.0, abduction: -0.9 },
      pinky: { mcp: 8.8, pip: 6.4, dip: 5.1, abduction: -0.6 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'O',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 1949 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 20.0, pip: 13.7, dip: 0.0, abduction: -36.0 },
      index: { mcp: 49.6, pip: 61.9, dip: 25.8, abduction: -1.9 },
      middle: { mcp: 51.7, pip: 70.3, dip: 27.0, abduction: 0.0 },
      ring: { mcp: 47.0, pip: 72.1, dip: 26.3, abduction: -1.1 },
      pinky: { mcp: 47.2, pip: 54.1, dip: 25.7, abduction: -2.2 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'P',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1999 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 19.9, pip: 12.2, dip: 0.0, abduction: 107.4 },
      index: { mcp: 20.2, pip: 4.6, dip: 3.5, abduction: 110.5 },
      middle: { mcp: 96.1, pip: 81.0, dip: 60.4, abduction: 0.0 },
      ring: { mcp: 106.7, pip: 84.9, dip: 65.0, abduction: -1.7 },
      pinky: { mcp: 104.9, pip: 77.4, dip: 71.6, abduction: -0.7 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 18.4, pip: 15.9, dip: 0.0, abduction: -101.4 },
      index: { mcp: 52.7, pip: 6.8, dip: 6.3, abduction: -90.9 },
      middle: { mcp: 95.5, pip: 84.2, dip: 49.9, abduction: 0.0 },
      ring: { mcp: 101.6, pip: 87.0, dip: 56.1, abduction: 2.5 },
      pinky: { mcp: 99.8, pip: 84.7, dip: 56.9, abduction: -1.6 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'Q',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1995 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 36.5, pip: 36.6, dip: 0.0, abduction: 23.4 },
      index: { mcp: 41.8, pip: 15.6, dip: 10.9, abduction: 10.6 },
      middle: { mcp: 38.0, pip: 123.8, dip: 39.5, abduction: 0.0 },
      ring: { mcp: 30.4, pip: 134.1, dip: 30.5, abduction: -7.6 },
      pinky: { mcp: 42.7, pip: 123.0, dip: 28.3, abduction: -8.0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 27.7, pip: 20.9, dip: 0.0, abduction: -42.9 },
      index: { mcp: 46.8, pip: 40.8, dip: 22.0, abduction: -26.3 },
      middle: { mcp: 65.4, pip: 76.8, dip: 42.1, abduction: 0.0 },
      ring: { mcp: 77.4, pip: 77.5, dip: 37.8, abduction: 2.5 },
      pinky: { mcp: 84.6, pip: 70.5, dip: 38.2, abduction: -2.4 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'R',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1911 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 26.8, pip: 29.6, dip: 0.0, abduction: -7.5 },
      index: { mcp: 18.3, pip: 9.6, dip: 8.8, abduction: 0.0 },
      middle: { mcp: 72.0, pip: 97.6, dip: 58.3, abduction: 0.0 },
      ring: { mcp: 70.9, pip: 106.1, dip: 52.2, abduction: 1.4 },
      pinky: { mcp: 56.2, pip: 107.8, dip: 44.7, abduction: 0.8 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 20.5, pip: 29.7, dip: 0.0, abduction: -6.8 },
      index: { mcp: 42.4, pip: 6.2, dip: 4.2, abduction: -4.4 },
      middle: { mcp: 25.4, pip: 5.0, dip: 3.2, abduction: 0.0 },
      ring: { mcp: 12.2, pip: 5.5, dip: 3.5, abduction: 3.4 },
      pinky: { mcp: 27.9, pip: 5.8, dip: 4.3, abduction: 3.1 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'S',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 2000 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 26.9, pip: 36.3, dip: 0.0, abduction: 0.9 },
      index: { mcp: 55.9, pip: 112.6, dip: 34.8, abduction: -1.1 },
      middle: { mcp: 59.8, pip: 110.3, dip: 32.6, abduction: 0.0 },
      ring: { mcp: 47.9, pip: 115.2, dip: 31.5, abduction: 11.8 },
      pinky: { mcp: 18.8, pip: 12.7, dip: 8.5, abduction: 97.9 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 23.0, pip: 35.1, dip: 0.0, abduction: -34.0 },
      index: { mcp: 57.3, pip: 108.8, dip: 41.6, abduction: -0.4 },
      middle: { mcp: 60.4, pip: 107.7, dip: 40.5, abduction: 0.0 },
      ring: { mcp: 55.0, pip: 110.3, dip: 36.9, abduction: -3.7 },
      pinky: { mcp: 23.3, pip: 11.9, dip: 8.5, abduction: -70.2 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'T',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 2000 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 23.4, pip: 13.2, dip: 0.0, abduction: 83.7 },
      index: { mcp: 19.2, pip: 4.5, dip: 3.4, abduction: 100.1 },
      middle: { mcp: 80.5, pip: 88.5, dip: 49.3, abduction: 0.0 },
      ring: { mcp: 92.8, pip: 94.8, dip: 58.6, abduction: -4.8 },
      pinky: { mcp: 86.2, pip: 87.5, dip: 65.8, abduction: -5.3 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 21.9, pip: 19.3, dip: 0.0, abduction: -96.2 },
      index: { mcp: 33.6, pip: 6.3, dip: 6.9, abduction: -92.1 },
      middle: { mcp: 89.7, pip: 81.5, dip: 53.5, abduction: 0.0 },
      ring: { mcp: 102.4, pip: 86.0, dip: 60.6, abduction: 4.6 },
      pinky: { mcp: 101.1, pip: 79.2, dip: 64.2, abduction: 2.1 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'U',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 1985 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 19.7, pip: 9.1, dip: 0.0, abduction: -19.1 },
      index: { mcp: 26.5, pip: 26.2, dip: 11.9, abduction: -26.1 },
      middle: { mcp: 58.8, pip: 75.7, dip: 46.3, abduction: 0.0 },
      ring: { mcp: 70.9, pip: 82.1, dip: 45.8, abduction: 1.9 },
      pinky: { mcp: 76.8, pip: 73.5, dip: 47.0, abduction: 0.6 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'V',
    hands: 'one',
    confidence: 'data-derived',
    sourceNote: "Computed from 1972 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 31.7, pip: 36.4, dip: 0.0, abduction: -1.3 },
      index: { mcp: 10.2, pip: 3.4, dip: 4.4, abduction: 11.0 },
      middle: { mcp: 15.2, pip: 3.9, dip: 5.8, abduction: 0.0 },
      ring: { mcp: 34.8, pip: 127.0, dip: 20.5, abduction: -18.6 },
      pinky: { mcp: 41.1, pip: 119.4, dip: 20.3, abduction: -9.5 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'W',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1907 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 26.3, pip: 26.2, dip: 0.0, abduction: 0.1 },
      index: { mcp: 36.4, pip: 3.1, dip: 4.1, abduction: -10.6 },
      middle: { mcp: 36.9, pip: 4.0, dip: 3.3, abduction: 0.0 },
      ring: { mcp: 32.0, pip: 5.7, dip: 4.1, abduction: 9.4 },
      pinky: { mcp: 24.7, pip: 7.9, dip: 5.2, abduction: 15.2 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
    secondary: {
      thumb: { mcp: 27.0, pip: 22.4, dip: 0.0, abduction: 1.5 },
      index: { mcp: 32.6, pip: 5.0, dip: 3.9, abduction: 9.3 },
      middle: { mcp: 31.2, pip: 3.7, dip: 3.0, abduction: 0.0 },
      ring: { mcp: 27.3, pip: 3.3, dip: 3.9, abduction: -15.7 },
      pinky: { mcp: 19.6, pip: 5.7, dip: 5.7, abduction: -18.6 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'X',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1758 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 20.9, pip: 29.0, dip: 0.0, abduction: 45.7 },
      index: { mcp: 25.4, pip: 8.9, dip: 7.6, abduction: 97.1 },
      middle: { mcp: 80.2, pip: 80.6, dip: 49.9, abduction: 0.0 },
      ring: { mcp: 88.1, pip: 95.4, dip: 66.6, abduction: -2.5 },
      pinky: { mcp: 78.5, pip: 90.5, dip: 68.7, abduction: 0.9 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 22.0, pip: 27.0, dip: 0.0, abduction: -71.6 },
      index: { mcp: 25.9, pip: 5.6, dip: 6.3, abduction: -104.0 },
      middle: { mcp: 93.8, pip: 75.3, dip: 55.0, abduction: 0.0 },
      ring: { mcp: 103.0, pip: 87.7, dip: 63.0, abduction: 4.5 },
      pinky: { mcp: 98.8, pip: 80.4, dip: 61.6, abduction: 3.1 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: 'Y',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1965 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 20.3, pip: 12.2, dip: 0.0, abduction: -115.3 },
      index: { mcp: 21.9, pip: 8.5, dip: 6.6, abduction: -119.3 },
      middle: { mcp: 96.0, pip: 76.5, dip: 52.4, abduction: 0.0 },
      ring: { mcp: 112.9, pip: 71.8, dip: 67.2, abduction: 0.1 },
      pinky: { mcp: 117.7, pip: 64.5, dip: 71.9, abduction: -5.0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 17.0, pip: 19.4, dip: 0.0, abduction: 69.8 },
      index: { mcp: 28.5, pip: 5.9, dip: 6.3, abduction: 98.0 },
      middle: { mcp: 89.5, pip: 83.5, dip: 54.8, abduction: 0.0 },
      ring: { mcp: 98.4, pip: 89.1, dip: 65.2, abduction: -3.2 },
      pinky: { mcp: 94.2, pip: 85.6, dip: 66.4, abduction: 0.7 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },
  {
    signId: 'Z',
    hands: 'two',
    confidence: 'data-derived',
    sourceNote: "Computed from 1999 real captured hand-landmark samples (Kaggle 'Indian Sign Language Hand Landmarks Dataset' by eraakash). Joint angles are the per-sample median, not a guess.",
    primary: {
      thumb: { mcp: 30.0, pip: 11.0, dip: 0.0, abduction: 38.9 },
      index: { mcp: 62.9, pip: 7.9, dip: 13.0, abduction: -2.6 },
      middle: { mcp: 62.5, pip: 10.7, dip: 12.5, abduction: 0.0 },
      ring: { mcp: 57.9, pip: 11.8, dip: 14.8, abduction: 2.4 },
      pinky: { mcp: 45.2, pip: 10.9, dip: 13.2, abduction: 4.0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
    secondary: {
      thumb: { mcp: 29.6, pip: 11.8, dip: 0.0, abduction: -18.2 },
      index: { mcp: 32.4, pip: 8.1, dip: 7.3, abduction: 0.5 },
      middle: { mcp: 31.8, pip: 8.8, dip: 8.3, abduction: 0.0 },
      ring: { mcp: 29.8, pip: 8.8, dip: 9.4, abduction: -0.6 },
      pinky: { mcp: 25.0, pip: 8.3, dip: 5.8, abduction: -1.7 },
      wristRotation: 0,
      handOrientation: 'palm-in',
    },
  },

  // --- NUMBERS: 1-5 follow documented finger-count convention (unchanged from before) ---
  {
    signId: '1',
    hands: 'one',
    confidence: 'convention',
    sourceNote: 'Finger-count convention: one extended finger.',
    primary: {
      thumb: { mcp: 30, pip: 10, dip: 0, abduction: 10 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      ring: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      pinky: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '2',
    hands: 'one',
    confidence: 'convention',
    sourceNote: 'Finger-count convention: two extended fingers.',
    primary: {
      thumb: { mcp: 30, pip: 10, dip: 0, abduction: 10 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 10 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: -10 },
      ring: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      pinky: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '3',
    hands: 'one',
    confidence: 'convention',
    sourceNote: 'Finger-count convention: three extended fingers.',
    primary: {
      thumb: { mcp: 60, pip: 30, dip: 0, abduction: -10 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 10 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: -10 },
      pinky: { mcp: 90, pip: 90, dip: 90, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '4',
    hands: 'one',
    confidence: 'convention',
    sourceNote: 'Finger-count convention: four extended fingers, thumb tucked.',
    primary: {
      thumb: { mcp: 70, pip: 40, dip: 10, abduction: -20 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 10 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: -10 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '5',
    hands: 'one',
    confidence: 'convention',
    sourceNote: 'Finger-count convention: all five extended and spread.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 40 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 15 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 5 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: -5 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: -15 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },

  // --- NUMBERS: 0, 6-9 -- still no real dataset found, flagged placeholders ---
  {
    signId: '0',
    hands: 'one',
    confidence: 'placeholder-unconfirmed',
    sourceNote: 'No reliable source or dataset found yet -- needs a real numbers landmark dataset or ISLRTC video check.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '6',
    hands: 'one',
    confidence: 'placeholder-unconfirmed',
    sourceNote: 'No reliable source or dataset found yet -- needs a real numbers landmark dataset or ISLRTC video check.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '7',
    hands: 'one',
    confidence: 'placeholder-unconfirmed',
    sourceNote: 'No reliable source or dataset found yet -- needs a real numbers landmark dataset or ISLRTC video check.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '8',
    hands: 'one',
    confidence: 'placeholder-unconfirmed',
    sourceNote: 'No reliable source or dataset found yet -- needs a real numbers landmark dataset or ISLRTC video check.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
  {
    signId: '9',
    hands: 'one',
    confidence: 'placeholder-unconfirmed',
    sourceNote: 'No reliable source or dataset found yet -- needs a real numbers landmark dataset or ISLRTC video check.',
    primary: {
      thumb: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      index: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      middle: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      ring: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      pinky: { mcp: 0, pip: 0, dip: 0, abduction: 0 },
      wristRotation: 0,
      handOrientation: 'palm-out',
    },
  },
];